#! /usr/bin/perl

use strict;
use warnings;
use JSON qw(from_json to_json);

while (my $line = <STDIN>) {
    chomp $line;
    my $rows = from_json($line);
    for my $row (@$rows) {
        $row->{Info} =~ s/(?<=\W)-?(?:0x[0-9a-f]+|[0-9\.]+)|'.*?[^'\\]'|".*?[^\\]"/\?/gi
            if $row->{Info};
    }
    print to_json($rows, { ascii => 1 }), "\n";
}
